# Generated by Django 3.2 on 2021-05-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=1024)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Entrada', models.CharField(max_length=100)),
                ('password_Asociado', models.CharField(max_length=1024)),
                ('url_Asociado', models.URLField(max_length=1024)),
                ('detalles_Asociado', models.CharField(max_length=1024)),
                ('suario_Asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.usuario')),
            ],
        ),
    ]
