# Generated by Django 3.2 on 2021-06-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_Confianza',
        ),
    ]
