# Generated by Django 3.2 on 2021-06-05 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intentos_por_IP',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('contador', models.IntegerField(default=0)),
                ('ultima_peticion', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='chat_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigoTelegram',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiempo_de_vida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_telegram',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Username',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Vi',
            fields=[
                ('iv', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.usuario')),
            ],
        ),
    ]
