# Generated by Django 3.2.4 on 2021-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='salt',
            field=models.CharField(max_length=512),
        ),
    ]
