# Generated by Django 3.2 on 2021-06-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0002_auto_20210605_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='suario_Asociado',
            new_name='usuario_Asociado',
        ),
        migrations.CreateModel(
            name='Usuario_Confianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioRegistrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.usuario')),
            ],
        ),
    ]
