# Generated by Django 3.2.4 on 2021-06-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0002_alter_usuario_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='iv',
            field=models.CharField(max_length=512),
        ),
    ]
