# Generated by Django 3.2 on 2021-06-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0003_auto_20210605_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrada',
            new_name='Cuenta',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='nombre_Entrada',
            new_name='nombre_Cuenta',
        ),
    ]
