# Generated by Django 3.1.6 on 2021-03-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuenta', models.CharField(max_length=100)),
                ('password_asociado', models.CharField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
                ('detalles', models.CharField(max_length=1024)),
                ('usuario_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroU.usuario')),
            ],
        ),
    ]
