# Generated by Django 3.1.6 on 2021-04-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroU', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
