# Generated by Django 3.1.6 on 2021-04-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroU', '0003_cuenta_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
