# Generated by Django 3.1.6 on 2021-04-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroU', '0005_cuenta_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuenta',
            new_name='Entrada',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='nombre_cuenta',
            new_name='nombre_Entrada',
        ),
    ]
