# Generated by Django 3.2 on 2021-05-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroU', '0006_auto_20210402_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='detalles',
            new_name='detalles_Asociado',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='password_asociado',
            new_name='password_Asociado',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='usuario_asociado',
            new_name='suario_Asociado',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='url',
            new_name='url_Asociado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='Telefono',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='Username',
        ),
    ]
